// Données de révision extraites du fichier original, conservées sans suppression.
const plan=[{day:"Jeudi soir",items:[["18h30","CEJM : contrat, marché, finalités"],["19h30","Quiz CEJM complet"],["20h30","Rédaction : 1 cas droit ou management"]]},{day:"Vendredi",items:[["09h00","CEJM droit : contrat, responsabilité, travail, RGPD"],["14h00","CEJM économie : marché, croissance, État, politiques"],["17h00","CEJM management : performance, stratégie, motivation"],["20h00","Sujet CEJM en 45 min"]]},{day:"Samedi",items:[["09h30","Correction des erreurs CEJM"],["11h00","Culture générale : questions de corpus + essai"],["14h00","Digitalisation : CRM, site web, CRC"],["18h00","Flashcards ratées"]]},{day:"Dimanche",items:[["09h30","Révision finale CEJM"],["14h00","Culture générale : intro, plan, conclusion"],["16h30","Digitalisation : omnicanal, satisfaction, newsletter"],["20h00","Relecture légère"]]},{day:"Lundi",items:[["Matin","CEJM : cartes ratées uniquement"],["Soir","Culture générale : méthode + exemples"]]},{day:"Mardi",items:[["Matin","Culture générale : pas de nouveau contenu"],["Soir","Digitalisation : cas pratiques + définitions"]]},{day:"Mercredi",items:[["Matin","Digitalisation : CRM, satisfaction, site, AIDA"],["Épreuve","Répondre en appliquant au cas"]]}];
const courses=[
{m:"Culture générale",t:"Confrontation de documents",k:["Survoler le corpus : nature, auteurs, dates, titres.","Repérer les idées principales par document.","Comparer les documents : points communs, oppositions, nuances.","Répondre à la question posée au lieu de résumer mécaniquement.","Éviter l’avis personnel gratuit dans les questions de corpus.","Tous les documents utiles doivent être mobilisés."],f:"Réponse de corpus : idée directrice → appui documentaire → confrontation → bilan."},
{m:"Culture générale",t:"Essai argumenté",k:["Répondre à une question posée avec un point de vue argumenté.","Utiliser le corpus, les lectures de l’année et des exemples culturels ou personnels.","Le pronom je est possible mais la réflexion doit rester structurée.","Plan clair : thèse / nuance / dépassement possible.","Relire pour corriger l’orthographe et vérifier la réponse au sujet."],f:"Introduction : reformulation du sujet → tension/problématique → annonce de la démarche."},
{m:"CEJM",t:"Marché, offre et demande",k:["Le marché est le lieu réel ou virtuel de rencontre entre offre et demande.","Si la demande augmente et l’offre reste faible, le prix augmente.","Si l’offre augmente et la demande reste faible, le prix baisse.","Rôles du marché : ajustement, incitation, information.","CPP : atomicité, homogénéité, fluidité, mobilité, transparence."],f:"Prix = signal d’information sur la rareté et les tensions du marché."},
{m:"CEJM",t:"Asymétrie d’information et externalités",k:["Asymétrie : un acteur possède plus d’informations que l’autre.","Réduction : clauses, garanties, devoir d’information, documents justificatifs.","Externalité : effet positif ou négatif sur un tiers sans compensation financière.","Positive : implantation d’une école qui dynamise l’immobilier.","Négative : pollution, bruit, nuisances."],f:"Toujours donner un exemple concret."},
{m:"CEJM",t:"Contrat",k:["Liberté contractuelle : contracter ou non, choisir le cocontractant, fixer le contenu.","Force obligatoire : le contrat s’impose aux parties.","Bonne foi : loyauté, honnêteté, transparence.","Validité : consentement, capacité, objet/contenu licite et certain, cause/raison licite.","Vices du consentement : erreur, dol, violence."],f:"Droit : règle → faits → application → conclusion."},
{m:"CEJM",t:"Clauses contractuelles",k:["Clause pénale : somme prévue en cas d’inexécution.","Réserve de propriété : le vendeur reste propriétaire jusqu’au paiement complet.","Indexation : prix ajusté selon un indice.","Hardship : renégociation si changement économique important.","Limitative de responsabilité : limite la réparation due."],f:"Toujours relier la clause au risque qu’elle couvre."},
{m:"CEJM",t:"Responsabilités",k:["Responsabilité civile : réparer un dommage.","Conditions : dommage, faute, lien de causalité.","Contractuelle : contrat mal exécuté.","Délictuelle : dommage hors contrat.","Responsabilité pénale : sanctionner une infraction."],f:"Civile = réparer ; pénale = punir."},
{m:"CEJM",t:"Rôle de l’État et politiques économiques",k:["Allocation : cadre juridique du marché.","Redistribution : corriger les inégalités.","Relance : stimuler la demande, croissance et emploi.","Rigueur : freiner la demande, limiter inflation et déficit.","Structurelle : améliorer durablement compétitivité et croissance."],f:"Budgétaire = dépenses/impôts ; monétaire = taux d’intérêt/monnaie."},
{m:"CEJM",t:"Concurrence, innovation, propriété industrielle",k:["Entente : accord anticoncurrentiel.","Abus de position dominante : exploiter abusivement une puissance de marché.","Concentration : fusion, acquisition, entreprise commune.","Brevet : protection d’une invention, dépôt INPI, monopole temporaire.","Marque : signe distinctif renouvelable."],f:"Innovation : produit, procédé, organisation, marketing."},
{m:"CEJM",t:"Organisation et ressources",k:["Facteurs de production : travail, capital, connaissances, matières premières.","Gains de productivité : qualification, équipement, organisation.","Chaîne de valeur : activités principales et de soutien.","Activités créatrices de valeur : à garder au cœur de l’entreprise.","Activités faibles en valeur : externalisation possible."],f:"Ressources tangibles = matérielles ; intangibles = immatérielles."},
{m:"CEJM",t:"Finance d’entreprise",k:["BFR : besoin lié au décalage entre dépenses et recettes d’exploitation.","FRNG : ressources durables - dépenses d’investissement.","Compte de résultat : produits - charges = bénéfice ou perte.","Financement interne : CAF, cession d’actifs.","Financement externe : capital, emprunt, crédit-bail."],f:"Solvabilité = capacité à payer ses dettes."},
{m:"CEJM",t:"Management, performance et stratégie",k:["Finalités : financière/économique/sociétale selon la fiche.","Parties prenantes internes : salariés, dirigeants, actionnaires.","Externes : clients, fournisseurs, banques, État, concurrents.","Performance : atteindre les objectifs avec les moyens disponibles.","SWOT : forces/faiblesses internes, opportunités/menaces externes.","PESTEL : politique, économique, social, technologique, écologique, légal.","Porter : concurrents, entrants, substituts, clients, fournisseurs."],f:"Stratégies : domination par les coûts, différenciation, focalisation."},
{m:"CEJM",t:"Travail et motivation",k:["Contrat de travail : parties, salaire, fonction, lieu, durée.","CDI, CDD, CTT.","Clauses : essai, non-concurrence, confidentialité, mobilité.","Droits : grève, liberté syndicale.","Motivation : salaire, primes, participation, reconnaissance, responsabilités."],f:"Herzberg : facteurs d’hygiène et facteurs moteurs."},
{m:"CEJM",t:"Numérique, CNIL, RGPD, e-commerce",k:["Marketplace : plateforme intermédiaire entre vendeurs et acheteurs.","Modèles : traditionnel, publicité, freemium, abonnement, collaboratif.","CNIL : informe, contrôle et sanctionne sur les données personnelles.","Opt-in : consentement avant envoi commercial.","Contrat électronique : conditions, vérification, confirmation, rétractation 14 jours."],f:"RGPD : finalité, transparence, minimisation, sécurité, durée limitée."},
{m:"Digitalisation",t:"Marché et demande",k:["Types de marché : principal, substitution, amont, aval, géographique.","Structures : monopsone, monopole, oligopole, CPP.","Études : documentaire, quantitative, qualitative.","Indicateurs : part de marché valeur/volume, pénétration, fidélité, équipement, renouvellement."],f:"Part de marché valeur = ventes entreprise / ventes totales marché."},
{m:"Digitalisation",t:"Site web",k:["Arborescence : structure des pages par thème.","Sites : vitrine, catalogue, institutionnel, e-commerce.","Maillage : liens internes entre pages.","Cahier des charges : objectifs, contraintes, fonctionnalités, graphisme, technique.","Nom de domaine : adresse du site.","Hébergement : mutualisé ou dédié.","Ergonomie : menu, recherche, fil d’Ariane, formulaire."],f:"Pages clés : accueil, contact, à propos, produits, mentions légales, FAQ."},
{m:"Digitalisation",t:"CRC et appels",k:["CRC : relation client à distance.","Acteurs : téléopérateur, télévendeur, téléconseiller.","Appel entrant : CERC = Contact, Écoute, Réponse, Conclusion.","Appel sortant : CROC = Contact, Raison, Objet, Congé.","Réclamation : insatisfaction entre promesse et résultat."],f:"Bonne réception : rapidité, empathie, efficacité."},
{m:"Digitalisation",t:"Newsletter, email et contenu",k:["Newsletter : email d’information envoyé à des abonnés consentants.","Avantages : leads, conversion, CTA, ciblage, coût faible, automatisation.","Limites : spam, désinscription, faible ouverture.","AIDA : Attention, Intérêt, Désir, Action.","Inbound : attirer par le contenu.","Outbound : pousser un message vers le consommateur.","Brand content : contenu centré marque.","Content marketing : contenu utile centré audience."],f:"Landing page = page conçue pour convertir en lead."},
{m:"Digitalisation",t:"Concurrence et benchmark",k:["Concurrence : entreprises du même marché avec offres similaires.","Barrières à l’entrée : brevet, distribution, fidélité client.","Étude de concurrence : identifier, comparer, exploiter les informations.","Benchmarking : comparer les pratiques pour progresser."],f:"Objectif : trouver un avantage concurrentiel."},
{m:"Digitalisation",t:"Omnicanal, CRM et satisfaction",k:["Multicanal : canaux utilisés séparément.","Cross canal : canaux successifs et connectés.","Omnicanal : canaux simultanés, parcours sans couture.","CRM : collecter, analyser, utiliser, mesurer les données clients.","Satisfaction : repérer les points de friction et fidéliser.","NPS : recommandation.","CES : effort client.","Verbatims : mots exacts des clients."],f:"CRM = vue unique du client."}
];
const glossary=[
["CEJM","Marché","Lieu réel ou virtuel de rencontre entre offre et demande."],["CEJM","Prix","Signal qui informe sur la rareté et les tensions du marché."],["CEJM","Asymétrie d’information","Situation où un acteur possède plus d’informations que l’autre."],["CEJM","Externalité","Impact d’un agent sur un tiers sans compensation financière."],["CEJM","Dol","Tromperie volontaire destinée à obtenir le consentement."],["CEJM","Erreur","Croyance fausse portant sur un élément essentiel du contrat."],["CEJM","Violence","Contrainte physique ou morale pour faire signer."],["CEJM","Bonne foi","Loyauté, honnêteté et transparence dans le contrat."],["CEJM","Clause pénale","Somme prévue en cas d’inexécution."],["CEJM","Responsabilité civile","Obligation de réparer un dommage."],["CEJM","Responsabilité pénale","Sanction d’un comportement interdit par la loi."],["CEJM","PIB","Richesse produite sur un territoire pendant une période."],["CEJM","Inflation","Hausse durable et générale des prix."],["CEJM","SWOT","Forces, faiblesses, opportunités, menaces."],["CEJM","PESTEL","Analyse macro-environnementale."],["CEJM","BFR","Décalage entre dépenses et recettes d’exploitation."],["Culture générale","Confrontation de documents","Mise en relation de plusieurs documents pour répondre à une question de corpus."],["Culture générale","Essai","Réponse argumentée et nuancée avec point de vue, corpus et exemples."],["Digitalisation","CRM","Outil de gestion de la relation client."],["Digitalisation","Omnicanal","Fusion des canaux pour un parcours sans rupture."],["Digitalisation","NPS","Score de recommandation client."],["Digitalisation","CES","Score d’effort client."],["Digitalisation","CERC","Contact, Écoute, Réponse, Conclusion."],["Digitalisation","CROC","Contact, Raison, Objet, Congé."],["Digitalisation","AIDA","Attention, Intérêt, Désir, Action."]];
const quizBank=[
{m:"CEJM",t:"Économie",q:"Si la demande augmente fortement alors que l’offre reste limitée, le prix tend à…",a:["Augmenter","Baisser","Rester fixe","Disparaître"],c:0,e:"La rareté relative fait monter le prix."},
{m:"CEJM",t:"Économie",q:"Les trois rôles du marché sont…",a:["Ajustement, incitatif, informatif","Social, fiscal, juridique","Production, stockage, vente","Croissance, emploi, inflation"],c:0,e:"Le prix ajuste, incite et informe."},
{m:"CEJM",t:"Économie",q:"Une entreprise forme ses salariés, ce qui améliore aussi le bassin d’emploi local. C’est une…",a:["Externalité positive","Externalité négative","Clause pénale","Politique de rigueur"],c:0,e:"Un tiers bénéficie de l’action sans payer directement."},
{m:"CEJM",t:"Économie",q:"Une banque exige bulletins de salaire et avis d’imposition avant un prêt pour réduire…",a:["L’asymétrie d’information","La croissance externe","La clause d’indexation","La focalisation"],c:0,e:"Elle cherche à mieux connaître le risque."},
{m:"CEJM",t:"Économie",q:"La politique de relance budgétaire consiste notamment à…",a:["Augmenter les dépenses publiques ou réduire les impôts","Augmenter les taux d’intérêt","Réduire toute demande","Interdire la concurrence"],c:0,e:"Elle vise croissance et emploi."},
{m:"CEJM",t:"Économie",q:"Le déficit commercial existe lorsque…",a:["Les importations dépassent les exportations","Les exportations dépassent les importations","Le PIB augmente","Les prix baissent"],c:0,e:"C’est un déséquilibre extérieur."},
{m:"CEJM",t:"Droit",q:"La force obligatoire du contrat signifie que…",a:["Le contrat s’impose aux parties","Le contrat est toujours gratuit","Le contrat est facultatif après signature","Le contrat ne crée jamais d’obligation"],c:0,e:"Les parties doivent respecter leurs engagements."},
{m:"CEJM",t:"Droit",q:"Un vendeur ment volontairement sur la constructibilité d’un terrain. Il y a…",a:["Dol","Erreur seule","Violence","Monopsone"],c:0,e:"Le vendeur provoque l’erreur."},
{m:"CEJM",t:"Droit",q:"La clause de réserve de propriété permet au vendeur de…",a:["Rester propriétaire jusqu’au paiement complet","Rompre le contrat sans raison","Augmenter le prix sans indice","Interdire toute négociation"],c:0,e:"Elle protège contre le non-paiement."},
{m:"CEJM",t:"Droit",q:"Responsabilité civile : conditions cumulatives ?",a:["Dommage, faute, lien de causalité","Erreur, dol, violence","Offre, demande, prix","Travail, capital, matière"],c:0,e:"Sans l’une d’elles, la responsabilité civile est fragilisée."},
{m:"CEJM",t:"Droit",q:"Responsabilité pénale et civile : différence principale ?",a:["Pénale = punir ; civile = réparer","Pénale = réparer ; civile = recruter","Pénale = manager ; civile = vendre","Aucune différence"],c:0,e:"La pénale protège la société."},
{m:"CEJM",t:"Droit",q:"Une entreprise collecte des emails sans consentement commercial. Notion concernée ?",a:["RGPD / opt-in","Dol uniquement","FRNG","PESTEL"],c:0,e:"L’usage commercial suppose un consentement clair."},
{m:"CEJM",t:"Management",q:"Finalités principales selon la fiche CEJM ?",a:["Financière, économique, sociétale","Pénale, civile, commerciale","Directe, courte, longue","Amont, aval, géographique"],c:0,e:"La sociétale intègre salariés, éthique, développement durable."},
{m:"CEJM",t:"Management",q:"Dans SWOT, les opportunités relèvent du…",a:["Diagnostic externe","Diagnostic interne","Compte de résultat","Contrat de travail"],c:0,e:"Externe = opportunités et menaces."},
{m:"CEJM",t:"Management",q:"Une entreprise rachète un concurrent : croissance…",a:["Externe","Organique uniquement","Interne","Passive"],c:0,e:"Rachat, fusion, acquisition = croissance externe."},
{m:"CEJM",t:"Management",q:"Une marque mise sur l’image premium et le service. Stratégie ?",a:["Différenciation","Domination par les coûts","Politique de rigueur","Entente"],c:0,e:"Elle cherche à être perçue comme unique."},
{m:"CEJM",t:"Organisation",q:"Externaliser une activité peu créatrice de valeur permet surtout de…",a:["Se concentrer sur le cœur de métier","Supprimer toute dépendance","Créer automatiquement un brevet","Annuler le contrat"],c:0,e:"C’est une logique de chaîne de valeur."},
{m:"CEJM",t:"Travail",q:"Clause de non-concurrence valable si elle est notamment…",a:["Limitée et compensée financièrement","Illimitée et gratuite","Toujours orale","Toujours interdite"],c:0,e:"Elle encadre une liberté du salarié."},
{m:"Culture générale",t:"Corpus",q:"Dans une réponse à une question de corpus, il faut…",a:["Confronter les documents sans avis personnel gratuit","Donner uniquement son opinion","Utiliser surtout des exemples extérieurs","Ignorer les documents difficiles"],c:0,e:"La réponse doit s’appuyer sur les documents et répondre précisément à la question."},
{m:"Culture générale",t:"Corpus",q:"Un paragraphe efficace sur corpus commence plutôt par…",a:["Une idée qui répond à la question","Une anecdote personnelle","Une opinion tranchée sans document","Une conclusion générale hors sujet"],c:0,e:"Puis on justifie avec un ou plusieurs documents."},
{m:"Culture générale",t:"Essai",q:"Dans l’essai, les exemples sont…",a:["Obligatoires ou fortement attendus","Interdits","Uniquement issus du corpus","Toujours juridiques"],c:0,e:"Ils soutiennent ton argumentation et peuvent venir du corpus, des lectures ou de ta culture."},
{m:"Culture générale",t:"Méthode",q:"QQQOCCP sert à…",a:["Analyser le sujet","Calculer une part de marché","Sanctionner une faute","Mesurer le NPS"],c:0,e:"Qui, Quoi, Quand, Où, Comment, Combien, Pourquoi."},
{m:"Digitalisation",t:"Marché",q:"Une étude qualitative sert surtout à…",a:["Comprendre en profondeur les besoins et attitudes","Mesurer un grand échantillon uniquement","Rédiger un contrat","Calculer la TVA"],c:0,e:"Elle explore les motivations."},
{m:"Digitalisation",t:"Site web",q:"Un site catalogue se distingue du site vitrine car il…",a:["Présente les produits avec détails, références ou prix","Vend toujours en ligne","Ne contient aucune offre","Remplace le CRM"],c:0,e:"Il va plus loin que la simple présentation."},
{m:"Digitalisation",t:"Site web",q:"Le maillage interne sert à…",a:["Relier les pages et faciliter la navigation","Héberger le site","Créer un nom de domaine","Supprimer les cookies"],c:0,e:"Il aide aussi le parcours utilisateur."},
{m:"Digitalisation",t:"CRC",q:"La méthode CERC concerne…",a:["Les appels entrants","Les appels sortants","La synthèse de documents","Le SWOT"],c:0,e:"Contact, Écoute, Réponse, Conclusion."},
{m:"Digitalisation",t:"CRC",q:"La méthode CROC concerne…",a:["Les appels sortants","Les appels entrants","La responsabilité civile","La croissance"],c:0,e:"Contact, Raison, Objet, Congé."},
{m:"Digitalisation",t:"Newsletter",q:"AIDA signifie…",a:["Attention, Intérêt, Désir, Action","Analyse, Idée, Droit, Achat","Accueil, Information, Devis, Accord","Actif, Interne, Durable, Aval"],c:0,e:"Structure classique d’un message commercial."},
{m:"Digitalisation",t:"Omnicanal",q:"Le parcours client sans couture correspond à…",a:["L’omnicanal","Le monocanal","Le monopsone","Le contrat pénal"],c:0,e:"Les canaux sont fusionnés et cohérents."},
{m:"Digitalisation",t:"CRM",q:"Un CRM permet principalement de…",a:["Collecter, analyser, utiliser et mesurer les données clients","Produire le PIB","Signer un CDD","Créer un brevet"],c:0,e:"Il offre une vue unique du client."},
{m:"Digitalisation",t:"Satisfaction",q:"Le CES mesure…",a:["L’effort fourni par le client","La recommandation uniquement","Le chiffre d’affaires","Le coût d’achat"],c:0,e:"Moins l’effort est élevé, plus la fidélité peut augmenter."},
{m:"Digitalisation",t:"Benchmark",q:"Le benchmarking consiste à…",a:["Comparer ses pratiques à celles d’autres entreprises","Fixer une peine pénale","Faire une synthèse objective","Augmenter les taux d’intérêt"],c:0,e:"But : progresser en s’inspirant des meilleurs."}
];
const flashcards=[...glossary.map(g=>[g[0],g[1],g[2]]),["CEJM","Rôles du marché ?","Ajustement, incitatif, informatif."],["CEJM","Conditions de validité du contrat ?","Consentement, capacité, objet/contenu licite et certain, cause/raison licite."],["CEJM","5 forces de Porter ?","Concurrents, entrants, substituts, clients, fournisseurs."],["CEJM","Modes de financement interne ?","CAF et cession d’actifs."],["CEJM","Modes de financement externe ?","Capital, emprunt, crédit-bail."],["Digitalisation","Types d’études ?","Documentaire, quantitative, qualitative."],["Digitalisation","Types de sites web ?","Vitrine, catalogue, institutionnel, e-commerce."],["Digitalisation","Types de contenus digitaux ?","Textes, audios, images, vidéos."],["Culture générale","Réponse sur corpus ?","Idée directrice, appui documentaire, confrontation, bilan."],["Culture générale","Règle majeure des questions de corpus ?","Répondre à la question avec les documents, sans avis personnel gratuit."]];
const cases=[
{title:"CEJM — Contrat et dol",text:"Un vendeur affirme qu’un terrain est constructible alors qu’il sait qu’il ne l’est pas. L’acheteur signe. Analyse juridiquement la situation.",structure:["Règle : consentement non vicié","Définir dol","Appliquer aux faits","Conclure : annulation possible / responsabilité"]},
{title:"CEJM — Responsabilité civile",text:"Une entreprise livre une machine défectueuse qui cause une perte financière au client. Analyse la responsabilité possible.",structure:["Identifier contrat ou hors contrat","Rappeler dommage/faute/lien causal","Appliquer","Conclure sur réparation"]},
{title:"CEJM — Management et CRM",text:"Une entreprise déploie un CRM mais les salariés refusent de l’utiliser. Analyse les enjeux et propose des solutions.",structure:["Définir CRM et changement","Résistances","Impact performance/relation client","Formation, communication, accompagnement","Conclusion"]},
{title:"CEJM — Stratégie",text:"Une marque premium refuse de baisser ses prix malgré des concurrents moins chers. Elle mise sur l’image, le service et la qualité. Analyse sa stratégie.",structure:["Diagnostic concurrentiel","Différenciation","Avantages/risques","Indicateurs de performance"]},
{title:"Culture générale — Corpus",text:"Explique la méthode à suivre pour répondre efficacement à des questions sur corpus.",structure:["Lire les questions avant le corpus","Identifier la thèse de chaque document","Répondre directement à la question","Confronter les documents","Conclure par un bilan"]},
{title:"Culture générale — Essai",text:"Selon vous, le numérique permet-il toujours de mieux communiquer ?",structure:["Reformuler","Problématiser","Arguments nuancés","Exemples","Conclusion claire"]},
{title:"Digitalisation — Satisfaction",text:"Une entreprise reçoit de nombreux avis négatifs après des commandes en ligne. Propose une démarche de mesure et d’amélioration.",structure:["Définir satisfaction","Collecter verbatims/enquêtes","NPS/CES","Actions correctives","Suivi"]},
{title:"Digitalisation — Newsletter",text:"Une entreprise veut lancer une newsletter commerciale. Propose la structure et les précautions à respecter.",structure:["Objectif/cible","AIDA","Objet clair/CTA","Désinscription","Consentement opt-in"]},
{title:"Digitalisation — Site web",text:"Une PME veut créer un site pour présenter ses services et générer des contacts. Propose les éléments essentiels.",structure:["Type de site","Arborescence","Ergonomie","Formulaire/CTA","Mentions légales/cookies"]}
];
const methods={cejm:[["Économie","Définir la notion → expliquer le mécanisme → appliquer au cas → conséquence."],["Droit","Règle de droit → faits → application → conclusion juridique."],["Management","Diagnostic → notion → analyse → solutions → indicateurs."],["Calculs","Écrire la formule, poser le calcul, interpréter le résultat."]],francais:[["Questions sur corpus","Répondre précisément, confronter les documents et conclure par un bilan."],["Essai","Reformuler le sujet → problématiser → argumenter → nuancer → conclure."],["Développement","Une idée par paragraphe, avec exemples interprétés."],["Thème annuel","Mobiliser les références étudiées pendant l’année."]],digital:[["Cas digital","Définition → diagnostic → outils → action → indicateurs."],["CRM","Collecter → analyser → utiliser → mesurer."],["CRC","Entrant = CERC ; sortant = CROC."],["Satisfaction","Verbatims + enquêtes + NPS/CES + actions correctives."]]};

courses.push(
{m:"Culture générale",t:"Épreuve CGE 2025-2026 : questions de corpus + essai",k:["L’épreuve écrite dure 3 heures.","Le corpus contient 2 à 3 documents de nature différente, liés au thème annuel.","Première partie : répondre à 2 à 4 questions nuancées et argumentées sur le corpus.","Deuxième partie : choisir un sujet d’essai parmi deux propositions.","L’essai mobilise le corpus, les lectures de l’année et des connaissances personnelles.","La synthèse de documents n’est plus le format de l’épreuve ponctuelle depuis la session 2025."],f:"Méthode 2026 : comprendre les documents → confronter les idées → répondre précisément → construire un essai nuancé."},
{m:"Culture générale",t:"Thème 2026 : Les animaux et nous",k:["Problématique : imaginer, connaître et comprendre l’animal.","Axes utiles : représentation, domestication, fascination, peur, exploitation, protection.","Notions à maîtriser : anthropomorphisme, spécisme, animalisation, déshumanisation, domestication, maltraitance.","Exemples mobilisables : fables, récits mythologiques, documentaires, débats sur l’élevage ou les zoos.","En essai, éviter le catalogue : chaque exemple doit soutenir une idée."],f:"Question type : notre rapport aux animaux révèle-t-il surtout notre humanité ?"},
{m:"Culture générale",t:"Répondre aux questions sur corpus",k:["Lire d’abord les questions pour cibler la lecture.","Identifier la thèse de chaque document et son ton : informatif, polémique, littéraire, iconographique.","Répondre à la question posée, sans réciter tout le document.","Confronter les documents quand la question l’exige.","Citer brièvement ou reformuler précisément une idée du corpus.","Conclure chaque réponse par une phrase de bilan."],f:"Réponse solide = idée directrice + appui sur documents + nuance."},
{m:"Culture générale",t:"Réussir l’essai",k:["Choisir le sujet où tu as le plus d’exemples précis.","Reformuler le sujet en tension : oui / mais / jusqu’où.","Faire 2 ou 3 parties courtes, chacune avec argument + exemple + lien au thème.","Mobiliser au moins un document du corpus et une référence personnelle.","Nuancer : limites, contre-argument, condition.","Finir par une réponse nette à la question."],f:"Plan efficace : thèse → nuance → dépassement ou conditions."},
{m:"Digitalisation",t:"E5 : relation client à distance et digitalisation",k:["L’épreuve écrite prend la forme d’une étude de cas liée à une organisation réelle.","Les problématiques portent sur la relation client omnicanale et digitale.","Compétences attendues : créer et entretenir la relation à distance, exploiter la data client, mesurer la performance.","Le cas peut demander de produire ou améliorer des contenus digitaux.","Le candidat doit justifier ses choix avec des indicateurs."],f:"Réponse E5 = contexte → diagnostic → action digitale → indicateurs → risques."},
{m:"Digitalisation",t:"Indicateurs digitaux à interpréter",k:["Taux d’ouverture : part des destinataires qui ouvrent un email.","Taux de clic : part des destinataires qui cliquent sur un lien.","Taux de conversion : part des visiteurs ou contacts qui réalisent l’action attendue.","Taux de rebond : part des visiteurs qui quittent une page sans interaction.","Panier moyen : chiffre d’affaires / nombre de commandes.","Coût d’acquisition client : dépenses marketing / nouveaux clients."],f:"Un indicateur ne suffit jamais : il faut l’interpréter avec l’objectif et le contexte."},
{m:"Digitalisation",t:"RGPD et relation client digitale",k:["Finalité : dire pourquoi les données sont collectées.","Minimisation : ne collecter que les données nécessaires.","Consentement : accord libre, spécifique, éclairé et univoque quand il est requis.","Droits : accès, rectification, effacement, opposition.","Sécurité : limiter les accès, protéger les fichiers, tracer les traitements.","Durée : ne pas conserver les données indéfiniment."],f:"Dans un cas digital, proposer une action commerciale sans conformité RGPD fragilise la copie."},
{m:"CEJM",t:"Méthode CEJM en dossier documentaire",k:["Identifier le champ dominant : économie, droit ou management.","Extraire les faits utiles du dossier, pas tout le contexte.","Mobiliser la notion exacte avant d’appliquer.","Construire une réponse argumentée et contextualisée.","Finir par une conséquence ou une décision opérationnelle.","Ne pas juxtaposer les cours : chaque notion doit éclairer le cas."],f:"Copie CEJM attendue : analyse + documents + notion + décision."},
{m:"CEJM",t:"Décision stratégique et diagnostic",k:["Le diagnostic interne repère ressources, compétences, forces et faiblesses.","Le diagnostic externe repère opportunités, menaces, marché, concurrence et environnement.","Une décision stratégique engage l’entreprise durablement.","Les indicateurs permettent de vérifier l’efficacité de la décision.","Une recommandation doit être cohérente avec les moyens de l’entreprise."],f:"Diagnostic → problème → options → choix justifié → indicateurs."}
);

glossary.push(
["Culture générale","Corpus","Ensemble de documents proposés au candidat et liés au thème annuel."],
["Culture générale","Essai","Réponse argumentée et nuancée à un sujet, appuyée sur le corpus, les cours et la culture personnelle."],
["Culture générale","Thèse","Idée principale défendue dans un texte ou dans une partie d’argumentation."],
["Culture générale","Nuance","Limite ou précision qui évite une réponse trop simpliste."],
["Culture générale","Anthropomorphisme","Attribution de caractéristiques humaines à un animal, un objet ou une entité non humaine."],
["Culture générale","Spécisme","Hiérarchisation des êtres vivants selon leur espèce, souvent au profit de l’humain."],
["Digitalisation","Taux d’ouverture","Pourcentage de destinataires ayant ouvert un email ou une newsletter."],
["Digitalisation","Taux de clic","Pourcentage de destinataires ou visiteurs ayant cliqué sur un lien."],
["Digitalisation","Taux de conversion","Pourcentage de personnes réalisant l’action attendue : achat, inscription, demande de contact."],
["Digitalisation","Taux de rebond","Part des visiteurs quittant une page sans interaction mesurable."],
["Digitalisation","Coût d’acquisition client","Dépenses engagées pour obtenir un nouveau client."],
["Digitalisation","Opt-out","Possibilité donnée au destinataire de se désinscrire ou refuser une sollicitation."],
["CEJM","Diagnostic interne","Analyse des ressources, compétences, forces et faiblesses de l’entreprise."],
["CEJM","Diagnostic externe","Analyse du marché, de la concurrence, de l’environnement et des parties prenantes."],
["CEJM","Décision stratégique","Choix durable qui engage l’entreprise et modifie sa trajectoire."],
["CEJM","Avantage concurrentiel","Élément permettant à l’entreprise de se distinguer durablement de ses concurrents."]
);

quizBank.push(
{m:"Culture générale",t:"Épreuve 2026",q:"Depuis la session 2025, l’épreuve ponctuelle de Culture générale et expression comporte principalement…",a:["Des questions sur corpus et un essai","Une synthèse de documents et une écriture personnelle","Un QCM et une dictée","Un oral de négociation"],c:0,e:"Le nouveau format officiel prévoit une partie questions sur corpus et une partie essai, chacune notée sur 10."},
{m:"Culture générale",t:"Corpus",q:"Une réponse solide à une question sur corpus doit surtout…",a:["Répondre précisément à la question en s’appuyant sur les documents","Résumer tous les documents dans l’ordre","Donner uniquement son avis personnel","Citer longuement un seul document"],c:0,e:"La réponse attendue est ciblée, argumentée et fondée sur le corpus."},
{m:"Culture générale",t:"Essai",q:"Dans l’essai de Culture générale, les exemples doivent…",a:["Soutenir un argument et être reliés au sujet","Être accumulés sans analyse","Venir uniquement du corpus","Remplacer la problématique"],c:0,e:"Un exemple vaut des points s’il éclaire une idée et fait avancer la réponse."},
{m:"Culture générale",t:"Essai",q:"La meilleure problématisation d’un sujet consiste à…",a:["Repérer une tension ou une limite dans la question","Transformer le sujet en définition de cours","Répondre oui ou non dès l’introduction sans nuance","Éviter toute prise de position"],c:0,e:"L’essai valorise une pensée nuancée, pas une réponse mécanique."},
{m:"Culture générale",t:"Thème 2026",q:"Pour le thème 2026, la notion d’anthropomorphisme désigne…",a:["Le fait d’attribuer des caractéristiques humaines à l’animal","Le refus de toute relation avec les animaux","Une méthode de calcul statistique","La disparition des espèces domestiques"],c:0,e:"Cette notion aide à analyser les représentations de l’animal dans les textes et images."},
{m:"Culture générale",t:"Thème 2026",q:"Dans un essai sur le rapport humain-animal, une copie solide doit éviter…",a:["Le catalogue d’exemples sans idée directrice","La nuance dans les arguments","L’appui sur le corpus","Une conclusion qui répond au sujet"],c:0,e:"Les exemples doivent être sélectionnés et interprétés, pas simplement listés."},
{m:"Culture générale",t:"Lecture",q:"Face à un document iconographique dans le corpus, il faut d’abord…",a:["Identifier ce qui est représenté, le point de vue et l’effet produit","Ignorer le document car ce n’est pas un texte","Le décrire sans le relier au sujet","Le remplacer par un exemple personnel"],c:0,e:"Un document visuel se lit aussi : composition, message, contexte, lien au thème."},
{m:"Culture générale",t:"Argumentation",q:"Un argument nuancé est un argument qui…",a:["Reconnaît une limite ou une condition à l’idée défendue","Change de sujet au milieu du paragraphe","Utilise seulement des connecteurs compliqués","Refuse toute prise de position"],c:0,e:"La nuance montre que tu sais raisonner et éviter les réponses simplistes."},
{m:"Digitalisation",t:"E5",q:"Dans une étude de cas E5, une recommandation digitale est convaincante si elle…",a:["Répond au problème du cas et prévoit des indicateurs de suivi","Liste tous les réseaux sociaux existants","Ignore les contraintes de l’entreprise","Se limite à définir le CRM"],c:0,e:"Le jury attend une action adaptée au contexte, justifiée et mesurable."},
{m:"Digitalisation",t:"Emailing",q:"Une newsletter a un bon taux d’ouverture mais un faible taux de clic. L’action prioritaire est plutôt de…",a:["Améliorer le contenu, l’offre et les appels à l’action","Changer uniquement l’heure d’envoi","Supprimer le lien de désinscription","Conclure que la campagne est parfaite"],c:0,e:"L’objet attire, mais le message ne transforme pas assez l’attention en action."},
{m:"Digitalisation",t:"E-commerce",q:"Un taux de rebond élevé sur une page produit peut indiquer…",a:["Une page peu pertinente, lente ou insuffisamment rassurante","Une fidélité client très forte","Une excellente conversion","Une absence totale de visiteurs"],c:0,e:"Le rebond signale souvent un problème d’expérience, de ciblage ou de contenu."},
{m:"Digitalisation",t:"CRM",q:"Une fiche client incomplète dans le CRM risque surtout de…",a:["Réduire la personnalisation et la qualité du suivi commercial","Garantir automatiquement la conformité RGPD","Augmenter mécaniquement le panier moyen","Remplacer le besoin de reporting"],c:0,e:"La data client sert à comprendre, personnaliser, suivre et mesurer la relation."},
{m:"Digitalisation",t:"RGPD",q:"Collecter la date de naissance d’un prospect sans utilité commerciale claire pose surtout un problème de…",a:["Minimisation des données","Taux de clic","Maillage interne","CROC"],c:0,e:"Le RGPD impose de collecter seulement les données nécessaires à une finalité déterminée."},
{m:"Digitalisation",t:"Omnicanal",q:"Un client commence une réclamation sur le chat puis doit tout répéter au téléphone. Le problème principal est…",a:["Une rupture dans le parcours omnicanal","Une hausse du taux de conversion","Une bonne exploitation du dossier client","Une stratégie de différenciation réussie"],c:0,e:"L’omnicanal suppose continuité, cohérence et partage de l’information entre canaux."},
{m:"Digitalisation",t:"Performance",q:"Pour évaluer une campagne d’acquisition, l’indicateur le plus directement lié au coût des nouveaux clients est…",a:["Le coût d’acquisition client","Le taux de rebond uniquement","La durée de conservation RGPD","La clause pénale"],c:0,e:"Le CAC rapporte les dépenses marketing ou commerciales au nombre de nouveaux clients obtenus."},
{m:"Digitalisation",t:"Contenu digital",q:"Un contenu digital utile en inbound marketing doit d’abord…",a:["Répondre à un besoin de la cible pour attirer le prospect","Interrompre le client sans ciblage","Masquer l’identité de l’entreprise","Supprimer tout appel à l’action"],c:0,e:"L’inbound attire par la valeur du contenu avant de convertir."},
{m:"CEJM",t:"Méthode",q:"Dans une réponse CEJM, l’erreur la plus pénalisante est souvent de…",a:["Réciter une notion sans l’appliquer au cas","Citer un fait du dossier","Conclure clairement","Identifier le champ droit, économie ou management"],c:0,e:"L’épreuve évalue la capacité à mobiliser les notions pour éclairer une situation d’entreprise."},
{m:"CEJM",t:"Droit",q:"Si un contrat est signé après une manœuvre volontaire destinée à tromper l’autre partie, le vice du consentement est…",a:["Le dol","La clause pénale","L’externalité","Le monopsone"],c:0,e:"Le dol suppose une tromperie intentionnelle ayant provoqué le consentement."},
{m:"CEJM",t:"Droit",q:"Une clause limitative de responsabilité sert principalement à…",a:["Plafonner la réparation due en cas de dommage, si elle est valable","Transférer automatiquement la propriété","Fixer un salaire minimum","Créer une entente anticoncurrentielle"],c:0,e:"Elle encadre le risque juridique, mais peut être écartée dans certains cas."},
{m:"CEJM",t:"Économie",q:"Une externalité négative justifie souvent l’intervention publique car…",a:["Le coût subi par les tiers n’est pas intégré dans le prix de marché","La demande disparaît toujours","Le contrat devient automatiquement nul","La concurrence devient parfaite"],c:0,e:"L’État peut corriger les défaillances de marché par réglementation, taxe, subvention ou information."},
{m:"CEJM",t:"Management",q:"Une décision stratégique se distingue d’une décision opérationnelle car elle…",a:["Engage durablement l’entreprise et son positionnement","Concerne uniquement une tâche quotidienne","Ne nécessite aucun diagnostic","Est toujours prise par un client"],c:0,e:"La stratégie engage l’entreprise à moyen ou long terme et modifie ses choix majeurs."},
{m:"CEJM",t:"Management",q:"Dans un diagnostic SWOT, une compétence forte de l’équipe commerciale est…",a:["Une force interne","Une menace externe","Une opportunité externe","Une politique monétaire"],c:0,e:"Les forces et faiblesses sont internes ; les opportunités et menaces sont externes."},
{m:"CEJM",t:"Finance",q:"Un BFR qui augmente fortement peut signaler…",a:["Un besoin de financement lié aux stocks, créances ou délais de paiement","Une absence totale d’activité","Une baisse automatique du chiffre d’affaires","Une clause de réserve de propriété"],c:0,e:"Le BFR vient du décalage entre décaissements et encaissements d’exploitation."},
{m:"CEJM",t:"Travail",q:"Une clause de mobilité est valable notamment si elle…",a:["Définit une zone géographique précise et respecte l’intérêt de l’entreprise","Permet de muter partout dans le monde sans limite","Supprime le contrat de travail","Remplace la rémunération"],c:0,e:"Les clauses du contrat de travail doivent être encadrées et proportionnées."}
);

flashcards.push(
["Culture générale","Format CGE ponctuel depuis 2025 ?","3 h : questions sur corpus /10 + essai /10."],
["Culture générale","Que doit faire une réponse sur corpus ?","Répondre précisément, confronter si demandé, s’appuyer sur les documents."],
["Culture générale","Essai CGE : sources à mobiliser ?","Corpus, lectures de l’année, cours et culture personnelle."],
["Culture générale","Thème 2026 ?","Les animaux et nous : imaginer, connaître, comprendre l’animal."],
["Culture générale","Anthropomorphisme ?","Attribution de caractéristiques humaines à un animal ou non-humain."],
["Culture générale","Spécisme ?","Hiérarchisation des espèces, souvent au profit de l’humain."],
["Digitalisation","Formule taux de conversion ?","Conversions / visiteurs ou contacts x 100."],
["Digitalisation","Formule coût d’acquisition client ?","Dépenses d’acquisition / nouveaux clients."],
["Digitalisation","Différence taux d’ouverture / taux de clic ?","Ouverture = email ouvert ; clic = action sur un lien."],
["Digitalisation","RGPD : minimisation ?","Collecter seulement les données nécessaires à la finalité."],
["Digitalisation","Réponse E5 solide ?","Contexte, diagnostic, action digitale, indicateurs, limites."],
["CEJM","Réponse CEJM solide ?","Notion exacte, faits du dossier, application, conséquence ou décision."],
["CEJM","Diagnostic interne ?","Forces et faiblesses : ressources, compétences, organisation."],
["CEJM","Diagnostic externe ?","Opportunités et menaces : marché, concurrence, environnement."],
["CEJM","Décision stratégique ?","Choix durable qui engage l’entreprise et son positionnement."]
);

cases.push(
{title:"Culture générale — Questions sur corpus",text:"Un corpus oppose deux représentations de l’animal : l’animal comme compagnon proche de l’humain et l’animal comme ressource exploitée. Rédige une réponse de 12 à 15 lignes à la question : comment les documents montrent-ils une relation ambivalente entre humains et animaux ?",structure:["Formuler une réponse directe à la question","Identifier au moins deux idées du corpus","Confronter les documents au lieu de les résumer séparément","Employer une nuance claire","Conclure par un bilan"]},
{title:"Culture générale — Essai 2026",text:"Sujet : mieux connaître les animaux conduit-il nécessairement à mieux les respecter ? Construis un essai argumenté et nuancé.",structure:["Reformuler la tension du sujet","Construire 2 ou 3 axes argumentatifs","Mobiliser le thème 2026 et au moins deux exemples précis","Nuancer avec une limite ou un contre-argument","Répondre clairement en conclusion"]},
{title:"Digitalisation — Campagne email",text:"Une PME obtient 48 % d’ouverture sur sa newsletter mais seulement 1,2 % de clics. Le dirigeant veut augmenter les demandes de devis. Analyse la situation et propose des améliorations mesurables.",structure:["Interpréter ouverture et clic","Identifier le problème de conversion","Proposer objet, contenu, CTA, landing page","Prévoir A/B test et segmentation","Choisir des indicateurs de suivi"]},
{title:"Digitalisation — Parcours omnicanal",text:"Un client contacte l’entreprise par formulaire, puis par téléphone. Le conseiller ne retrouve pas l’historique et le client répète sa demande. Analyse le dysfonctionnement et propose une solution CRM.",structure:["Définir omnicanal et CRM","Identifier la rupture du parcours","Proposer centralisation de la data client","Prévoir procédure et formation","Mesurer satisfaction, délai, résolution"]},
{title:"CEJM — Diagnostic et décision",text:"Une entreprise commerciale subit une baisse de marge malgré une hausse du chiffre d’affaires. Elle hésite entre baisser ses prix, améliorer son service ou revoir ses coûts. Établis un diagnostic et conseille une décision.",structure:["Distinguer chiffre d’affaires, marge et coûts","Mobiliser diagnostic interne/externe","Identifier plusieurs options stratégiques","Justifier la décision avec le contexte","Proposer des indicateurs de suivi"]}
);

methods.francais = [
["Épreuve ponctuelle 2026","3 h : questions sur corpus /10 puis essai /10. La synthèse n’est plus le format ponctuel depuis la session 2025."],
["Questions sur corpus","Réponse directe → appui précis sur documents → confrontation → nuance → mini-bilan."],
["Essai","Reformuler le sujet → problématiser → 2 ou 3 axes → exemples interprétés → conclusion qui répond."],
["Thème 2026","Les animaux et nous : représentations, domestication, exploitation, protection, rapport humain-animal."]
];

methods.digital.push(
["E5 écrit","Étude de cas : contexte réel, relation client à distance, digitalisation, e-commerce, indicateurs."],
["Indicateurs","Ouverture, clic, conversion, rebond, panier moyen, coût d’acquisition : toujours interpréter selon l’objectif."],
["RGPD","Finalité, minimisation, consentement, droits, sécurité, durée de conservation."]
);

methods.cejm.push(
["Dossier documentaire","Sélectionner les faits utiles, mobiliser la notion exacte, appliquer, décider."],
["Recommandation","Une solution CEJM doit être argumentée, contextualisée et accompagnée d’indicateurs."]
);
